// Code generated by golang.org/x/tools/cmd/bundle. DO NOT EDIT.
//go:generate bundle -o abc159/A/bundled_gen.go -pkg main -dst github.com/mpppk/atcoder/abc159/A github.com/mpppk/atcoder/gen

// go:generate goofy mustify --file input.go
//

package B

func lib_ReverseStr(s string) string {
	runes := []rune(s)
	for i, j := 0, len(runes)-1; i < j; i, j = i+1, j-1 {
		runes[i], runes[j] = runes[j], runes[i]
	}
	return string(runes)
}

